ESH/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static ESH.Models.ESHDBModels;

namespace ESH.Models
{
    public partial class ShoppingCart
    {
        ESHDBContext db = new ESHDBContext();
        string ShoppingCartId { get; set; }
        public const string CartSessionKey = "CartId";

        public static ShoppingCart GetCart (HttpContextBase context)
        {
            var cart = new ShoppingCart();
            cart.ShoppingCartId = cart.GetCartId(context);
            return cart;
        }
        public static ShoppingCart GetCart (Controller controller)
        {
            return GetCart(controller.HttpContext);
        }
        public int AddToCart (Product product)
        {
            var cartItem = db.Carts.SingleOrDefault(
                c => c.CartId == ShoppingCartId
                && c.ProductId == product.id);
            if(cartItem == null)
            {
                cartItem = new Cart
                {
                    ProductId = product.id,
                    CartId = ShoppingCartId,
                    Count = 1,
                    DateCreate = DateTime.Now
                };
                db.Carts.Add(cartItem);
            }
            else
            {
                cartItem.Count++;
            }
            db.SaveChanges();
            return cartItem.Count;
        }

        public int RemoveFromCart (int id)
        {
            var cartItem = db.Carts.Single(
                cart => cart.CartId == ShoppingCartId
                && cart.ProductId == id);

            int itemCount = 0;

            if (cartItem != null)
            {
                if (cartItem.Count > 1)
                {
                    cartItem.Count--;
                    itemCount = cartItem.Count;
                }
                else
                {
                    db.Carts.Remove(cartItem);
                }
                db.SaveChanges();
            }
            return itemCount;
        }

        public void EmptyCart()
        {
            var CartItems = db.Carts.Where(
                cart => cart.CartId == ShoppingCartId);
            foreach (var cartItem in CartItems)
            {
                db.Carts.Remove(cartItem);
            }
            db.SaveChanges();
        }

        public List<Cart> GetCartItems()
        {
            return db.Carts.Where(
                cart => cart.CartId == ShoppingCartId).ToList();
        }   

        public int GetCount()
        {
            int? count = (from cartItems in db.Carts
                          where cartItems.CartId == ShoppingCartId
                          select (int?)cartItems.Count).Sum();
            return count ?? 0;
        }

        public decimal GetTotal()
        {
            decimal? total = (from cartItems in db.Carts
                              where cartItems.CartId == ShoppingCartId
                              select (int?)cartItems.Count *
                              cartItems.Products.Price).Sum();
            return total ?? decimal.Zero;
        }
        public Order CreateOrder(Order order)
        {
            decimal orderTotal = 0;
            order.OrderDetails = new List<OrderDetails>();

            var cartItems = GetCartItems();

            foreach (var item in cartItems)
            {
                var orderDetail = new OrderDetails
                {

                    ProductId = item.ProductId,
                    OrderId = order.id,
                    UnitPrice = item.Products.Price,
                    Quantity = item.Count
                };
                orderTotal += (item.Count * item.Products.Price);
           
                order.OrderDetails.Add(orderDetail);
                db.OrderDetails.Add(orderDetail);


            }

            foreach (var temp in order.OrderDetails)
            {
                var idpost = temp.Products.ArticlePos;
                var token = Core.GetFromNetlabs.GetToken();
                var ostatok = Core.GetFromNetlabs.GetOstatok(token, idpost);
                if (temp.Products.PaymentOnline != true)
                {
                    order.PayOnline = false;
                    order.StatusOrderId = 1;
                    break;
                }
                
               
                   else if (ostatok==0)
                {
                    order.PayOnline = false;
                    order.StatusOrderId = 1;
                    break;
                }

                else
                {
                    order.PayOnline = true;
                    order.StatusOrderId = 3;
                }
               


            }

            order.Total = orderTotal;
            order.TotalSumm = orderTotal + order.ShippingSumm;
            db.Entry(order).State = EntityState.Modified;
            db.SaveChanges();  /*Все в порядке*/
            EmptyCart();
            return order;
        }

        public string GetCartId (HttpContextBase context)
        {
            if (context.Session[CartSessionKey] == null)
            {
                if (! string.IsNullOrWhiteSpace(context.User.Identity.Name))
                {
                    context.Session[CartSessionKey] =
                        context.User.Identity.Name;
                }
                else
                {
                    Guid tempCartId = Guid.NewGuid();
                    context.Session[CartSessionKey] = tempCartId.ToString();
                }
            }
            return context.Session[CartSessionKey].ToString();
        }

        public void MigrateCart(string userName)
        {
            var shoppingCart = db.Carts.Where(
                c => c.CartId == ShoppingCartId);
            foreach (Cart item in shoppingCart)
            {
                item.CartId = userName;
            }
            db.SaveChanges();
        }
    }
}

ESH/Controllers/ProductsController.cs
using ESH.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using static ESH.Models.ESHDBModels;

namespace ESH.Controllers
{
    public class ProductsController : Controller
    {
        ESHDBContext db = new ESHDBContext();
        // GET: Catalogy
        public async Task<ActionResult> Item(string URL)
        {
            var develiry = db.DeveliryPrices.ToList();
            ViewBag.develiry = develiry;

            string tip = null;
            if (URL != null)
            {
                Product prodUrl = await db.Products.FirstOrDefaultAsync(p => p.Url == URL);
                Product product = await db.Products.Include(c => c.Category).Include(m => m.Manufacturers).Include(p => p.SkladTypes).FirstOrDefaultAsync(p => p.id == prodUrl.id);
                var img = db.Imgs.Where(i => i.ProductId == product.id).ToList();
                ViewBag.img = img;
                decimal oldprice = 0;
                var stock = db.Stocks.Include(s => s.Products).Include(s => s.StockTypes).Where(s => s.ProductId == product.id);
                if (stock.Count() > 0)
                {
                    foreach (var st in stock)
                    {
                        switch (st.StockTypeid)
                        {
                            case 1:
                                ViewData["StockType"] = "rassrochka.png";
                                 oldprice = (product.PriceOpt * 20/100) + product.PriceOpt;
                                var i = Convert.ToInt32(oldprice);
                                if (i < 3000)
                                { if (i % 10 != 0) i = (i / 10) * 10 + 10; }
                                else
                                {
                                    if (i % 100 != 0) i = (i / 100) * 100 + 100;
                                }
                                oldprice = i;
                                break;
                            case 2:
                                ViewData["StockType"] = "rasprodaja.png";
                                oldprice = (product.PriceOpt * 20/100) + product.PriceOpt;
                                 i = Convert.ToInt32(oldprice);
                                if (i < 3000)
                                { if (i % 10 != 0) i = (i / 10) * 10 + 10; }
                                else
                                {
                                    if (i % 100 != 0) i = (i / 100) * 100 + 100;
                                }
                                oldprice = i;
                                break;
                            default:
                                ViewData["StockType"] = "no.png";
                                break;
                        }
                    }
                }
                else
                {
                    ViewData["StockType"] = "no.png";
                }
        
                if (product.CategoryId!=25 && product.CategoryId !=24)
                {
                    ViewBag.OldPrice = oldprice;
                }
                else
                {
                    ViewBag.OldPrice = 0;
                }
                var complect = db.Complects.Where(x => x.Productid == product.id).Include(p => p.Products).ToList();
                if (complect.Count() > 0) { ViewBag.complect = complect; }
                var propuctComplect = db.Products.ToList();
                ViewBag.propuctComplect = propuctComplect;
                var OS = db.PropertyAlls.Include(p => p.PropertyNames).Where(x => x.ProductId == product.id).SingleOrDefault(x => x.PropertyNames.Name == "Операционная система");
                if (OS != null)
                {
                    if (OS.PropertyValue == "Windows 10")
                    {
                        ViewData["OS"] = "Win10logo.png";
                    }
                    else
                    {
                        ViewData["OS"] = "no.png";
                    }
                }
                var proc = db.PropertyAlls.Include(p => p.PropertyNames).Where(x => x.ProductId == product.id).SingleOrDefault(x => x.PropertyNames.Name == "Процессор ноутбука");
                if (proc != null)
                {
                    switch (proc.PropertyValue)
                    {
                        case "Intel Core i3":
                            ViewData["proc"] = "i3.png";
                            break;
                        case "Intel Core i5":
                            ViewData["proc"] = "i5.png";
                            break;
                        case "Intel Core i7":
                            ViewData["proc"] = "i7.png";
                            break;
                        default:
                            ViewData["proc"] = "no.png";
                            break;
                    }
                }
         
                // вызов свойств
                var propall = db.PropertyAlls.Include(p => p.PropertyNames).Include(p => p.Products).Where(x => x.ProductId == product.id);
                ViewBag.propertyAll = propall;



                var property = db.Properties.Include(p => p.PropertyTypes).Include(p => p.PropertyValues).Where(p => p.ProductId == product.id).ToList();

                if (product.ManufacturerId != null) { ViewData["Brand"] = product.Manufacturers.Name; }
                else { ViewData["Brand"] = "не указан"; }
                var i3 = System.Convert.ToInt32(product.Price);
                var i2 = (i3 / 100) * 30;
                if (product.Price > 3000)
                {
                    ViewData["PriceCredit"] = "В кредит: " + "от " + (i3 + i2) / 24 + " руб./мес";
                }

                foreach (var tipPro in property)
                {
                    if (tipPro.PropertyTypeId == 2)
                    {
                        tip = tipPro.PropertyValues.Name;
                    }


                }
                if (tip != null) { ViewData["tip"] = tip; }
                else { ViewData["tip"] = "не указан"; }

                ViewBag.property = property;
                //---конец вызова свойств
                //походие товары
                var i4 = (i3 * 0.10) + i3;
                var i5 = (i3 * 0.10);
                var i6 = i3 - i5;
                var randowProduct = db.Products.Include(c => c.Category).Include(m => m.Manufacturers).Include(p => p.SkladTypes).Where(x => x.CategoryId == product.CategoryId).Where(x => x.ManufacturerId == product.ManufacturerId).Take(3);
                ViewBag.randowProduct = randowProduct;

                var imgrandowProduct = db.Imgs.ToList();
                ViewBag.imgrandowProduct = imgrandowProduct;
                //каталог
                var cat_children = db.Categories.Where(c => c.id == product.Category.ParentId).FirstOrDefault();

                var cat_parent = db.Categories.Where(c => c.id == cat_children.ParentId).FirstOrDefault();

                var cat = db.Categories.ToList();
                ViewBag.cat = cat;
                if (cat_parent != null)
                {
                    ViewBag.cat_parent = cat_parent.id;
                    ViewBag.cat_children = cat_children.id;
                }
                else
                {
                    ViewBag.cat_parent = cat_children.id;
                }


                var JoinProduct = db.JoinProducts.Where(p => p.ProductFirst == product.id).Include(c => c.Products);
                if (JoinProduct.Count() != 0)
                {
                    ViewBag.JoinProduct = JoinProduct;
                }
                else
                {
                    ViewBag.JoinProduct = null;
                }
                var sklad = db.Sklads.FirstOrDefault(s => s.ProductId == product.id);
                if (sklad != null)
                {
                    ViewData["sklad"] = "в  магазине - " + sklad.Count + " шт. ";
                }
                else
                {
                    ViewData["sklad"] = product.SkladTypes.Name;
                    var date = DateTime.Today.AddDays(+7);
                    ViewBag.Dostavka = date.ToString("ddd, dd MMM yyyy");
                    date = DateTime.Today.AddDays(+10);
                    ViewBag.Dostavka2 = date.ToString("ddd, dd MMM yyyy");

                }
                var proizvoditel = db.Properties.Where(p => p.PropertyTypes.id == 1).Include(p => p.PropertyTypes).Include(p => p.PropertyValues).ToList();
                ViewBag.proizvoditel = proizvoditel;
                return View(product);
            }
            else
            {
                return HttpNotFound();
            }

        }

        public ActionResult ListCatalogy()
        {

            return View(db.Categories.ToList());
        }
    }
}

ESH/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static ESH.Models.ESHDBModels;
using ESH.Models;
using ESH.ViewModel;

namespace ESH.Controllers
{
    public class ShoppingCartController : Controller
    {
        ESHDBContext db = new ESHDBContext();
        // GET: ShoppingCart
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            var develiry = db.DeveliryPrices.ToList();
            ViewBag.develiry = develiry;
            var img = db.Imgs.ToList();
            ViewBag.img = img;
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult AddToCart (int id)
        {
            var item = db.Products.Single(product => product.id == id);
            var cart = ShoppingCart.GetCart(this.HttpContext);
            int count = cart.AddToCart(item);
            var result = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(item.Name) + " Добавлен в корзину",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = count,
                DeleteId = id
            };
            return Json(result);
        }
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            string itemName = db.Products.Single(item => item.id == id).Name;
            int itemCount = cart.RemoveFromCart(id);
            var result = new ShoppingCartRemoveViewModel
            {
                Message = "Один (1)" + Server.HtmlEncode(itemName) +
                " был удален из корзины ",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(result);
        }
        [ChildActionOnly]
        public ActionResult CartSumm()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            if(cart.GetTotal()>0) ViewData["CartSumm"] = cart.GetTotal() + " руб.";

            if (cart.GetCount()>0)ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSumm");
        }
        [HttpPost]
        public ActionResult GetDeveliry(string develiry, string city)
        {
            var idcity = db.DeveliryPrices.SingleOrDefault(x => x.City == city).Id;
            
            return RedirectToAction("index", "Order", new { develiry = develiry, status = "new" , idcity=idcity });
        }
    }
}

ESH/Views/ShoppingCart/CartSumm.cshtml
<a href="@Url.Action("Index","ShoppingCart",null,null)" ><i class="fa fa-shopping-cart" style="padding-right:13px;"></i>  Корзина 
    @if (ViewData["CartCount"] == null)
    {
        <span>пусто</span>
            }
    else
    {
        <span id="cart-status" class="badge">@ViewData["CartCount"]</span>
        <span id="cart-summ"> @ViewData["CartSumm"]</span>
    }
 
    </a>

ESH/Views/ShoppingCart/Index.cshtml
@model ESH.ViewModel.ShoppingCartViewModel
@{
    ViewBag.Title = "Корзина покупателя";
    Layout = "~/Views/Shared/_Layout.cshtml";
 
}

<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".addcart").click(function () {
            // Get the id from the link
            var recordToAdd = $(this).attr("data-id");
            if (recordToAdd != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/AddToCart", { "id": recordToAdd },
                    function (data) {
                        $('#update-message').text(data.Message);
                        $('#cart-status').text(data.CartCount);
                        $('#cart-summ').text(data.CartTotal);


                    });
            }
        });
    });
</script>
<script type="text/javascript">
    $(function () {
        $(".RemoveLink").click(function () {
            var recordToDelete = $(this).attr("data-id");
            if (recordToDelete != '') {
                $.post("/ShoppingCart/RemoveFromCart",{"id":recordToDelete},
                    function (data) {
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeIn('show');
                        } else {
                            $('#item-count-' + data.DeleteId).text(data.ItemCount);
                        }
                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text(data.CartCount);
                    })
            }
        })
    })
</script>
@if (Model.CartItems.Count > 0)
            {
                using (Html.BeginForm("GetDeveliry", "ShoppingCart", FormMethod.Post))
                    {
    <section id = "cart_items" >


         <div class="container">
            <div class="table-responsive cart_info">
                <div id="update-message">
                </div>
                <table class="table table-condensed">
                    <thead>
                        <tr class="cart_menu">
                            <td class="image">Наименование</td>
                            <td class="description"></td>
                            <td class="price">Цена</td>
                            <td class="quantity">Количество</td>
                            <td class="total">Стоимость</td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model.CartItems)
                        {
                       
                            <tr>
                                <td class="cart_product">
                                    @if (item.Products.OneImg == true)
                                    {
                                    <a href='@Url.Action("Item", "Products",
                                                new { url = item.Products.Url }, null)'><img src="@item.Products.Img" height="80" /></a>
                                    }
                                    else
                                    {
                                        foreach (var img in ViewBag.img)
                                        {
                                            if (img.ProductId == item.Products.id)
                                            {
                                                if (img.in_first == true)
                                                {
                                                    <a href='@Url.Action("Item", "Products",
                                                new { url = item.Products.Url }, null)'><img src="@img.path_img@img.img" height="80" /></a>
                                                }

                                            }
                                        }
                                    }
  
                                    
                                </td>
                                <td class="cart_description" style="width:50%;">
                                    <h4><a href='@Url.Action("Item", "Products",
                                                new { url = item.Products.Url }, null)'>@item.Products.Name</a></h4>
                                    <p>артикул: @item.Products.Article</p>
                                </td>
                                <td class="cart_price">
                                    <p>@string.Format("{0:#,#}", item.Products.Price) <i class="fa fa-rub" aria-hidden="true"></i></p>
                                </td>
                                <td class="cart_quantity" style="width:11%;">
                                    <div class="cart_quantity_button">
                                        <a class="cart_quantity_up addcart" data-id="@item.ProductId" href="#"> + </a>
                                        <input class="cart_quantity_input" type="text" name="quantity" value="@item.Count" id="item-count-@item.ProductId" autocomplete="off" size="2">
                                        <a class="cart_quantity_down RemoveLink" href="#" 
                                   data-id="@item.ProductId"> - </a>
                                    </div>
                                </td>
                                <td class="cart_total" style="width:10%;">
                                    <p class="cart_total_price">@string.Format("{0:#,#}", item.Count*item.Products.Price) <i class="fa fa-rub" aria-hidden="true"></i></p>
                                </td>
                                <td class="cart_delete">
                                 
                                    <a class="RemoveLink"  data-id="@item.ProductId" href="#"><i class="fa fa-times"></i></a>
                                </td>
                            </tr>
                        }
                       
                  
                    </tbody>
                </table>
            </div>
        </div>
    </section> <!--/#cart_items-->
    <section id="do_action">
        <div class="container">
            <div class="heading">
                <h3>Способ получения заказа</h3>
      
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="chose_area">
                     
                        <ul class="user_option">
                            <li style="padding:15px 0;">

                                <label style="padding:0 25px">Город</label>


                                <select style="width:50%;margin-left:140px;" id="city" name="city">
                                    @foreach (var item in ViewBag.develiry)
                                    {
                                        <option id="@item.Id" >@item.City</option>
                                    }
                                
                                </select>
                            </li>
                         
                            <li style="padding:15px;">
                                <label>Самовывоз из пункта выдачи</label>
                                <input type="radio" style="width:100px;" name="develiry" id="develiry" value="magaz" data-toggle="tooltip" data-placement="left" title="Заказы Вы можите забрать в любое удобное для вас время в нашем пункет выдачи">
                              
                                
                            </li>
                         
                            <li style="padding:15PX">
                                <label>Курьерская доставка на дом</label>
                                <input type="radio" style="width:100px;margin-left:6px;" name="develiry" id="develiry" value="kurer"  data-toggle="tooltip" data-placement="left" title="Доставка по городу и области, а также в пределах ПФО. Стоимость доставки расчитывается при оформлении заказа ">
                      
                               
                            </li>  
                            
                        </ul>
              
                    
 
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="total_area">
                        <ul>
                            <li>Стоимость товаров в корзине  <span id="cartTotal">@Model.CartTotal р.</span></li>
                       
                        </ul>
                     
                        <input class="btn btn-default check_out" value="ОФОРМИТЬ ЗАКАЗ" type="submit"  >
                    </div>
                </div>
            </div>
        </div>
    </section><!--/#do_action-->
    }
}

else
{
    <section id="cart_items">
        <div class="container">
        <h4>Ваша корзина пуста </h4>
        </div>
    </section>

}

@*<script type="text/javascript">
    $(function () {
        var develiry = $("#develiry"),
            CartTotal = $("#cartTotal"),
            CartSum = $("#CartSum");
        develiry.change(function () {
            var del = parseInt(develiry.val());
            if (del == "kurer") {
                CartSum.text(CartTotal + 350);
            }
        })
    });
</script>*@